groups:
  - name: inference-alerts
    rules:
      - alert: HighInferenceLatency
        expr: histogram_quantile(0.9, sum(rate(inference_latency_seconds_bucket[2m])) by (le)) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Inference latency p90 > 1s"
          description: "Wecontainers should have more "
      - alert: HighInferenceRequestRate
        expr: rate(inference_requests_total[1m]) > 50
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High inference traffic"
          description: "We should have more containers"
