  # prometheus.yml
  global:
    scrape_interval: 5s

  scrape_configs:
    # trae datos de la APi de inferencia
    - job_name: 'inference_api'
      static_configs:
        - targets: ['inference_api:8989']
  rule_files:
    - /etc/prometheus/prometheus-rules.yml