apiVersion: v1
kind: Service
metadata:
  name: inference-api
  namespace: mlops
spec:
  selector:
    app: inference-api
  ports:
    - port: 80
      targetPort: 8989
      protocol: TCP
  type: ClusterIP
 