apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inference-api
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/<TU_USUARIO>/<TU_REPO>.git
    targetRevision: main
    path: k8s  # donde est√°n deployment-service.yaml, configmap, secret, etc.

  destination:
    server: https://kubernetes.default.svc
    namespace: mlops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
