apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: house-mlops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yhernandeze/proyecto_3.git
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-house
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
