apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlops-house
resources:
  - namespace.yaml
  - inference-api-deployment.yaml
  - inference-api-service.yaml
  - streamlit-deployment.yaml
  - streamlit-service.yaml
