# Example for documentation only.
apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets
  namespace: mlops
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "<minio-user>"
  AWS_SECRET_ACCESS_KEY: "<minio-pass>"
  MLFLOW_S3_ENDPOINT_URL: "http://host.docker.internal:9000"
 

  